"""
Convert CSRML XML files to JSON representation.

Generates:
  pyToxPrint/data/toxprint_V2.0_r711.json
  pyToxPrint/data/TxP_PFAS_v1.0.4.json

Usage::

    python convert_xml_to_json.py [--verbose]

The JSON format for each file is::

    {
      "id": "<document_id>",
      "title": "<title>",
      "csrml_version": "1" | "2",
      "n_bits": 729,            # or 129
      "bits": [
        {
          "id": "<subgraph_id>",
          "label": "<human_readable_name>",
          "smarts": "<SMARTS_string_or_null>",
          "exception_smarts": ["<SMARTS>", ...]
        },
        ...
      ]
    }

Notes
-----
- SMARTS strings are generated by a CSRML-to-SMARTS converter that handles the most
  common atom/bond condition types.  Complex conditions (matchingQueryAtom,
  combineAtomFeatures, atomDescriptorValue, elementGroup) are approximated or skipped.
- Patterns that fail RDKit validation are stored with 'smarts_valid': false.
- JSON is written to the data/ directory adjacent to this script.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Make sure parent package is importable
script_dir = Path(__file__).resolve().parent
sys.path.insert(0, str(script_dir.parent))

try:
    from rdkit import Chem
    _HAS_RDKIT = True
except ImportError:
    _HAS_RDKIT = False

from pyCSRML._csrml import parse_csrml_xml, ordered_bit_list

DATA_DIR = script_dir / "data"

SOURCES = [
    {
        "xml": DATA_DIR / "toxprint_V2.0_r711.xml",
        "json": DATA_DIR / "toxprint_V2.0_r711.json",
        "name": "ToxPrint v2.0",
    },
    {
        "xml": DATA_DIR / "TxP_PFAS_v1.0.4.xml",
        "json": DATA_DIR / "TxP_PFAS_v1.0.4.json",
        "name": "TxP_PFAS v1.0.4",
    },
]


def validate_smarts(smarts: str | None) -> bool:
    if not _HAS_RDKIT or not smarts:
        return smarts is not None
    mol = Chem.MolFromSmarts(smarts)
    return mol is not None


def convert(xml_path: Path, json_path: Path, name: str, verbose: bool = False):
    if not xml_path.exists():
        print(f"[SKIP] XML not found: {xml_path}")
        return

    print(f"Parsing {name} from {xml_path.name} …", flush=True)
    parsed = parse_csrml_xml(str(xml_path))
    bit_order = ordered_bit_list(parsed)

    n_ok = 0
    n_fail = 0
    bits = []

    for bit_id in bit_order:
        sg = parsed["subgraph_index"].get(bit_id)
        if sg is None:
            if verbose:
                print(f"  [WARN] subgraph {bit_id!r} referenced in hierarchy but not found")
            continue

        smarts = sg["smarts"]
        valid = validate_smarts(smarts)
        if valid:
            n_ok += 1
        else:
            n_fail += 1
            if verbose:
                print(f"  [FAIL] {bit_id}: smarts={smarts!r}")

        bits.append(
            {
                "id": sg["id"],
                "label": sg["label"],
                "smarts": smarts,
                "smarts_valid": valid,
                "exception_smarts": sg["exception_smarts"],
            }
        )

    spec = {
        "id": parsed["id"],
        "title": parsed["title"],
        "csrml_version": parsed["csrml_version"],
        "n_bits": len(bits),
        "n_valid": n_ok,
        "n_invalid": n_fail,
        "bits": bits,
    }

    json_path.parent.mkdir(parents=True, exist_ok=True)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(spec, f, ensure_ascii=False, indent=2)

    print(
        f"  → {len(bits)} bits, {n_ok} valid SMARTS, {n_fail} failed "
        f"→ {json_path.name}",
        flush=True,
    )


def main():
    parser = argparse.ArgumentParser(description="Convert CSRML XML to JSON")
    parser.add_argument("--verbose", "-v", action="store_true")
    args = parser.parse_args()

    for src in SOURCES:
        convert(src["xml"], src["json"], src["name"], verbose=args.verbose)

    print("Done.", flush=True)


if __name__ == "__main__":
    main()
